### ISSUE TITLE
Not a real issue, but a question

### ISSUE THREAD

**Issue by poseso** [Rudnev/laravel-settings#29]
Is your package compatible with stancl tenancy?

so it can be tenant aware ?

https://github.com/archtechx/tenancy
https://tenancyforlaravel.com/

I'm building a multi-tenant app, and was wondering if the package would be compatible so I can set settings for each individual tenant,

Thanks Andrei

**Comment by Rudnev** [comment]
Hello Carlos,

I need to look, i haven't used it. I'll try to answer in a few days.

**Comment by poseso** [comment]
Great! thanks again Andrei!

**Comment by Rudnev** [comment]
Basic conditions:
1. Use the multi-database tenancy;
2. Use the cache separation.

Unfortunaly, `\Stancl\Tenancy\Bootstrappers\CacheTenancyBootstrapper` won't work, because it does not intercept calls to `app('cache')->store()`. As a solution, create your own bootstrapper:
```php
<?php

namespace App\Bootstrappers;

use Illuminate\Contracts\Foundation\Application;
use Stancl\Tenancy\Contracts\TenancyBootstrapper;
use Stancl\Tenancy\Contracts\Tenant;

class SettingsTenancyBootstrapper implements TenancyBootstrapper
{
    protected $app;
    protected $cachePrefix;
    protected $cachePrefixConfigName = 'settings.stores.database.cache.prefix';

    public function __construct(Application $app)
    {
        $this->app = $app;
    }

    public function bootstrap(Tenant $tenant)
    {
        $this->cachePrefix = $this->cachePrefix ?? $this->app['config']->get($this->cachePrefixConfigName);
        $this->app['config']->set($this->cachePrefixConfigName, $this->cachePrefix . $tenant->getTenantKey());
    }

    public function revert()
    {
        $this->app['config']->set($this->cachePrefixConfigName, $this->cachePrefix);
        $this->cachePrefix = null;
    }
}
```
Then add the bootstrapper in the `config/tenancy.php` file:
```php
  'bootstrappers' => [
      Stancl\Tenancy\Bootstrappers\DatabaseTenancyBootstrapper::class,
      Stancl\Tenancy\Bootstrappers\CacheTenancyBootstrapper::class,
      Stancl\Tenancy\Bootstrappers\FilesystemTenancyBootstrapper::class,
      Stancl\Tenancy\Bootstrappers\QueueTenancyBootstrapper::class,
      // Stancl\Tenancy\Bootstrappers\RedisTenancyBootstrapper::class, // Note: phpredis is needed
      App\Bootstrappers\SettingsTenancyBootstrapper::class,
  ],
```
This still requires some testing, especially background tasks, but these are the basic things to take care of.

**Comment by poseso** [comment]
At the moment is working correctly, I'll make some tests to see if everything works as expected, Thanks again Andrei!, I'll close this
