### ISSUE TITLE
How to access default settings if a setting doesn't exists?

### ISSUE THREAD

**Issue by poseso** [Rudnev/laravel-settings#4]
[settings] => class@anonymous Object
        (
            [default:protected] => Array
                (
                    [timezone] => America/Santo_Domingo
                    [language] => es
                    [dateformat] => d-m-Y
                    [timeformat] => g:i A
                )

            [storage:ArrayObject:private] => Array
                (
                )

        )

if I want to get .  {{ settings()->get('dateformat') }} .  but dateformat doesn't exists... how do I get the default one ?

**Comment by Rudnev** [comment]
Hi @poseso,

If you want to get per-user settings, you can define $settingsConfig property in your model:

```php
use Rudnev\Settings\Trait\HasSettings;
use Illuminate\Database\Eloquent\Model;

class User extends Model 
{
    use HasSettings;
    
    protected $settingsConfig = [
        'default' => [
            'dateformat' => 'd-m-Y'
        ]
    ];
}
```

And I noticed that you're trying to get a global setting in the view, for the user settings there should be: 
```php
{{ $user->settings('dateformat') }}
```
or
```php
{{ $user->settings()->get('dateformat') }}
```

But if you want to get the default settings not for the model, you can write this code (for exmaple in your AppServiceProvider.php):
```php
settings()->setDefault('dateformat', 'd-m-Y')
```
and `{{ settings()->get('dateformat') }}` returned `d-m-Y`

**Comment by poseso** [comment]
Can there be an array of settings? like:

settings()->setDefault([
    'dateformat' => 'd-m-Y',
    'timeformat' => 'g:i A'
]);

??
