### ISSUE TITLE
Multiple queries for settings

### ISSUE THREAD

**Issue by poseso** [Rudnev/laravel-settings#6]
I'm doing something like this:

                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group @if ($errors->has('settings.company_name')) has-danger @endif">
                                        <label>{{ __('Nombre de la Empresa') }}</label>
                                        <input name="settings[company_name]" class="form-control" value="{{ old('settings.company_name', settings('company_name')) }}" autocomplete="company_name">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group @if ($errors->has('settings.company_contact')) has-danger @endif">
                                        <label>{{ __('Contacto') }}</label>
                                        <input name="settings[company_contact]" class="form-control" value="{{ old('settings.company_contact', settings('company_contact')) }}"  autocomplete="company_contact">
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group @if ($errors->has('settings.company_contact_position')) has-danger @endif">
                                        <label>{{ __('Cargo') }}</label>
                                        <input name="settings[company_contact_position]" class="form-control" value="{{ old('settings.company_contact_position', settings('company_contact_position')) }}"  autocomplete="company_contact_position">
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="form-group @if ($errors->has('settings.address')) has-danger @endif">
                                        <label>{{ __('Dirección') }}</label>
                                        <input name="settings[address]" class="form-control" value="{{ old('settings.address', settings('address')) }}"  autocomplete="address">
                                    </div>
                                </div>
                            </div>

the problem is that is making 1 query per each setting  instead of 1 query for all settings, do I have to make it different? for those 4 settings its making 4 queries

**Comment by Rudnev** [comment]
Hi, @poseso 

Please, show your config files settings.php and cache.php (with actual SETTINGS_DRIVER and CACHE_DRIVER values)

**Comment by poseso** [comment]
settings.php

<?php

return [
    /*
   |--------------------------------------------------------------------------
   | Default Settings Store
   |--------------------------------------------------------------------------
   |
   | This option controls the default connection that gets used while
   | using this library. This connection is used when another is
   | not explicitly specified when executing a given settings function.
   |
   | Supported: "array", "database"
   |
   */

    'default' => env('SETTINGS_DRIVER', 'database'),

    /*
    |--------------------------------------------------------------------------
    | Settings Stores
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the settings "stores" for your application as
    | well as their drivers. You may even define multiple stores for the
    | same settings driver to group types of items stored in your settings store.
    |
    */

    'stores' => [

        'array' => [
            // The driver name.
            'driver' => 'array',
        ],

        'database' => [
            // The driver name.
            'driver' => 'database',

            // The database connection from file "config/database.php".
            // If set to null or false, the default connection will be used.
            'connection' => null,

            /*
             |------------------------------------------------------------------
             |  Cache configuration:
             |------------------------------------------------------------------
             */
            'cache' => [
                // Enable / Disable caching.
                'enabled' => false,

                // Time to Live in minutes.
                'ttl' => 120,

                // The cache store from file "config/cache.php".
                // If set to null or false, the default store will be used.
                'store' => null,
            ],

            /*
             |------------------------------------------------------------------
             |  Names of tables and columns.
             |------------------------------------------------------------------
             */
            'names' => [
                'settings' => [
                    // The name of the table for storing app settings.
                    'table' => 'settings',

                    // The name of the scope column.
                    'scope' => 'scope',

                    // The name of the key column.
                    'key' => 'name',

                    // The name of the value column.
                    'value' => 'value',
                ],

                'settings_models' => [
                    // The name of the table for storing model settings.
                    'table' => 'settings_models',

                    // The prefix for polymorphic association.
                    'entity' => 'model',

                    // The name of the key column.
                    'key' => 'name',

                    // The name of the value column.
                    'value' => 'value',
                ],
            ],
        ],

        // Place the config for your custom store here:

        // ...

    ],

    /*
    |--------------------------------------------------------------------------
    | Events
    |--------------------------------------------------------------------------
    |
    | Enable / Disable events triggering.
    |
    */

    'events' => true,
];


cache.php

<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Default Cache Store
    |--------------------------------------------------------------------------
    |
    | This option controls the default cache connection that gets used while
    | using this caching library. This connection is used when another is
    | not explicitly specified when executing a given caching function.
    |
    | Supported: "apc", "array", "database", "file", "memcached", "redis"
    |
    */

    'default' => env('CACHE_DRIVER', 'file'),

    /*
    |--------------------------------------------------------------------------
    | Cache Stores
    |--------------------------------------------------------------------------
    |
    | Here you may define all of the cache "stores" for your application as
    | well as their drivers. You may even define multiple stores for the
    | same cache driver to group types of items stored in your caches.
    |
    */

    'stores' => [

        'apc' => [
            'driver' => 'apc',
        ],

        'array' => [
            'driver' => 'array',
        ],

        'database' => [
            'driver' => 'database',
            'table' => 'cache',
            'connection' => null,
        ],

        'file' => [
            'driver' => 'file',
            'path' => storage_path('framework/cache/data'),
        ],

        'memcached' => [
            'driver' => 'memcached',
            'persistent_id' => env('MEMCACHED_PERSISTENT_ID'),
            'sasl' => [
                env('MEMCACHED_USERNAME'),
                env('MEMCACHED_PASSWORD'),
            ],
            'options' => [
                // Memcached::OPT_CONNECT_TIMEOUT  => 2000,
            ],
            'servers' => [
                [
                    'host' => env('MEMCACHED_HOST', '127.0.0.1'),
                    'port' => env('MEMCACHED_PORT', 11211),
                    'weight' => 100,
                ],
            ],
        ],

        'redis' => [
            'driver' => 'redis',
            'connection' => 'default',
        ],

    ],

    /*
    |--------------------------------------------------------------------------
    | Cache Key Prefix
    |--------------------------------------------------------------------------
    |
    | When utilizing a RAM based store such as APC or Memcached, there might
    | be other applications utilizing the same cache. So, we'll specify a
    | value to get prefixed to all our keys so we can avoid collisions.
    |
    */

    'prefix' => env(
        'CACHE_PREFIX',
        str_slug(env('APP_NAME', 'laravel'), '_').'_cache'
    ),

];

**Comment by Rudnev** [comment]
In `settings.php` change
```php
                // Enable / Disable caching.
                'enabled' => false,
```
with
```php
                // Enable / Disable caching.
                'enabled' => true,
```

**Comment by poseso** [comment]
if I set new values via database, will it update? or ill have to php artisan clear:cache ?

**Comment by Rudnev** [comment]
` php artisan cache:forget laravel-settings`

Automatic update occurs in the following cases:
1) Run the migration CreateSettingsTable
2) Data change via Settigns :: set(), Settings :: forget(), Settings::flush() methods

**Comment by poseso** [comment]
So if i do this in my controller it should work?

        foreach ($request->all()['settings'] as $key => $val) {
           Settings::flush($key, $val);
            settings()->set($key, $val);
        }

flushing specific settings then setting them again ?

**Comment by Rudnev** [comment]
Easier:
```php
settings($request->all()['settings']);
```
This will overwrite specific settings and clear the cache.

**Comment by Rudnev** [comment]
Or even easier )
```php
settings($request->settings);
```

**Comment by poseso** [comment]
oh ok so I can then do my normal foreach

        foreach ($request->all()['settings'] as $key => $val) {
            // clear settings
            settings($request->all()['settings']);
            // set settings
            settings()->set($key, $val);
        }

is that correct?

**Comment by poseso** [comment]
Great, thanks!
